version: '3.7'

services:
  panel:
    build: "./"
    image: "${IMAGE_NAME}:${IMAGE_VERSION}"
    logging:
      driver: "json-file"
      options:
        max-file: "3"
        max-size: "100m"
    env_file:
     - env/prod.env
    expose:
     - "8001"
    ports:
      - "8001:8001"
    volumes:
    - /usr/src/data/logs:/usr/src/app/logs
    restart: on-failure
    environment:
      APP_PORT: 8001 
